services:
  php-epg:
    image: taksss/php-epg:latest
    container_name: php-epg
    # 数据目录映射
    volumes:
      - /etc/epg:/htdocs/data
    # 默认端口 5678
    ports:
      - "5678:80"
    depends_on:
      - mysql
      - phpmyadmin
    restart: unless-stopped 